#!/bin/bash
# Theme toggle script for Sway/Swayfx
# Syncs with Gnome when available, falls back to Sway-only theming

THEME_STATE_FILE="$HOME/.config/sway/.theme_state"
THEME_CONFIG_FILE="/tmp/sway_theme_config"

# Detect if running under Gnome
is_gnome_available() {
    command -v gsettings &>/dev/null && \
    gsettings get org.gnome.desktop.interface color-scheme &>/dev/null
}

# Get current theme state
get_current_theme() {
    if is_gnome_available; then
        # Use Gnome's setting as source of truth
        local gnome_scheme=$(gsettings get org.gnome.desktop.interface color-scheme)
        if [[ "$gnome_scheme" == *"dark"* ]]; then
            echo "dark"
        else
            echo "light"
        fi
    elif [[ -f "$THEME_STATE_FILE" ]]; then
        cat "$THEME_STATE_FILE"
    else
        echo "dark"  # Default to dark
    fi
}

# Toggle theme
toggle_theme() {
    local current=$(get_current_theme)
    local new_theme

    if [[ "$current" == "dark" ]]; then
        new_theme="light"
    else
        new_theme="dark"
    fi

    # Update Gnome if available
    if is_gnome_available; then
        if [[ "$new_theme" == "dark" ]]; then
            gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
            gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
        else
            gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
            gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita'
        fi
    fi

    # Save state for Sway
    echo "$new_theme" > "$THEME_STATE_FILE"

    # Generate Sway theme config
    generate_theme_config "$new_theme"

    # Update wofi theme
    update_wofi_theme "$new_theme"

    # Reload Sway to apply changes
    swaymsg reload &>/dev/null || true

    # Send notification if notify-send is available
    if command -v notify-send &>/dev/null; then
        if [[ "$new_theme" == "dark" ]]; then
            notify-send -t 2000 -u low "Theme" "Switched to Dark Mode 🌙"
        else
            notify-send -t 2000 -u low "Theme" "Switched to Light Mode ☀️"
        fi
    fi
}

# Generate Sway theme configuration based on theme
generate_theme_config() {
    local theme="$1"

    cat > "$THEME_CONFIG_FILE" << EOF
# Auto-generated theme configuration - Do not edit manually
# Generated by toggle_theme.sh

EOF

    if [[ "$theme" == "dark" ]]; then
        cat >> "$THEME_CONFIG_FILE" << 'EOF'
# Dark Theme - Color Variables (85% opacity = D9 in hex)
set $bg_color #323232
set $bar_bg_color #323232D9
set $text_color #ffffff
set $inactive_text #d0d0d0
set $border_color #404040
set $indicator_color #5294e2

# Client colors (window borders)
client.focused $indicator_color $indicator_color $text_color $indicator_color
client.unfocused $bg_color $bg_color $inactive_text $bg_color
client.focused_inactive $bg_color $bg_color $inactive_text $bg_color
EOF
    else
        cat >> "$THEME_CONFIG_FILE" << 'EOF'
# Light Theme - Color Variables (85% opacity = D9 in hex)
set $bg_color #f0f0f0
set $bar_bg_color #f0f0f0D9
set $text_color #000000
set $inactive_text #666666
set $border_color #d0d0d0
set $indicator_color #5294e2

# Client colors (window borders)
client.focused $indicator_color $indicator_color #ffffff $indicator_color
client.unfocused $bg_color $bg_color $inactive_text $bg_color
client.focused_inactive $bg_color $bg_color $inactive_text $bg_color
EOF
    fi
}

# Update wofi theme by symlinking the appropriate CSS file
update_wofi_theme() {
    local theme="$1"
    local wofi_dir="$HOME/.config/wofi"

    # Ensure wofi config directory exists
    mkdir -p "$wofi_dir"

    # Remove existing symlink or file
    rm -f "$wofi_dir/style.css"

    # Create symlink to appropriate theme
    if [[ "$theme" == "dark" ]]; then
        ln -s "$wofi_dir/style-dark.css" "$wofi_dir/style.css"
    else
        ln -s "$wofi_dir/style-light.css" "$wofi_dir/style.css"
    fi
}

# Initialize theme on startup
init_theme() {
    local current=$(get_current_theme)
    generate_theme_config "$current"
    update_wofi_theme "$current"
}

# Main command dispatcher
case "${1:-toggle}" in
    toggle)
        toggle_theme
        ;;
    init)
        init_theme
        ;;
    get)
        get_current_theme
        ;;
    *)
        echo "Usage: $0 {toggle|init|get}"
        exit 1
        ;;
esac
